### PR TITLE
Sorted packages.

### PR DESCRIPTION
**Pull request by vudaltsov**

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Thank you @vudaltsov.

**Comment by vudaltsov** [comment]
@nicolas-grekas , could you please merge this to higher branches as well?

**Comment by fabpot** [comment]
Indeed, @nicolas-grekas I let you do the merge.

**Comment by nicolas-grekas** [comment]
I'd be happy to, but there are two pending PRs before, would be great to have a look so that I do the merge only once.

**Pull request merged**
