### PR TITLE
Move symfony/debug-pack to require-dev

### PR DESCRIPTION
**Pull request by vudaltsov**

### CODE REVIEW

**Comment by vudaltsov** [comment]
We can also remove `symfony/profiler-pack` from the `dev` section because `symfony/debug-pack` requires it.

**Comment by fabpot** [comment]
I prefer to keep the explicitness of having `symfony/profiler-pack`. The only issue I can see with your proposal is Monologbundle, which is useful in the non-dev section. Perhaps it needs to be removed from the `debug-pack` and added explicitly here. WDTY?

**Comment by vudaltsov** [comment]
Agree with your point about explicitness.

`symfony/monolog-bundle` is already mentioned in the `require` section now. So my proposal will not cause `monolog-bundle` removal in `--no-dev`.

I would agree that logging and debugging are separate things. If you remove `monolog-bundle` from `debug-pack` than `easycorp/easy-log-handler` should be also removed and added explicitly to `require-dev` in the `website-skeleton`. But I think that might break someone's existing project...

**Comment by nicolas-grekas** [comment]
Thank you @vudaltsov.

**Pull request merged**
