### PR TITLE
[Composer] Use an optimized autoloader

### PR DESCRIPTION
**Pull request by lyrixx**

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Does that work with dev workflows?
Or does this means ppl will have to run composer install after every new class they create?

**Comment by lyrixx** [comment]
Good catch. I think I will remove the authoritative option

**Comment by nicolas-grekas** [comment]
optimize-autoloader has the same issue, isn't it?

**Comment by lyrixx** [comment]
Nope

**Comment by nicolas-grekas** [comment]
Yes, as soon as I rename a class  :)

**Comment by lyrixx** [comment]
Nope:

Here is a reproducer to confirm everything is OK:

```bash
composer create-project symfony/website-skeleton composer-opt
cd composer-opt

composer config optimize-autoloader true
composer install

bin/console make:subscriber MyCommand
vim src/EventSubscriber/MyCommandSubscriber.php
# I added: echo "OK"; 

bin/console about
# I can see the "OK"

mv src/EventSubscriber/MyCommandSubscriber{,2}.php
vim src/EventSubscriber/MyCommandSubscriber2.php 
# I edited the classname
bin/console about
# I can see the "OK"

composer install
# Let's be really sure !!!
mv src/EventSubscriber/MyCommandSubscriber{2,3}.php
vim src/EventSubscriber/MyCommandSubscriber3.php
# I edited the classname
bin/console about
# I can see the "OK"
```

**Comment by lyrixx** [comment]
For the record, I also tested with authoritative class and indeed it does not work:


```
composer config classmap-authoritative true
mv src/EventSubscriber/MyCommandSubscriber{3,4}.php
vim src/EventSubscriber/MyCommandSubscriber4.php
bin/console about
```
=> 
```
In FileLoader.php line 173:
                                                                                                                                                                         
  Expected to find class "App\EventSubscriber\MyCommandSubscriber4" in file "/tmp/composer-opt/src/EventSubscriber/MyCommandSubscriber4.php" while importing services f  
  rom resource "../src/*", but it was not found! Check the namespace prefix used with the resource in /tmp/composer-opt/config/services.yaml (which is loaded in resour  
  ce "/tmp/composer-opt/config/services.yaml").                                                                                                                          
                                                                                                                                                                         

In FileLoader.php line 206:
                                                                                                                                                                         
  Expected to find class "App\EventSubscriber\MyCommandSubscriber4" in file "/tmp/composer-opt/src/EventSubscriber/MyCommandSubscriber4.php" while importing services f  
  rom resource "../src/*", but it was not found! Check the namespace prefix used with the resource.                                                                      
```

So IMHO, this PR is fine as this

**Comment by nicolas-grekas** [comment]
[The doc of composer](https://getcomposer.org/doc/articles/autoloader-optimization.md
) has this mention:

image

Is it wrong? What's expected benefit from this PR also?

**Comment by lyrixx** [comment]
@seldaek Could you tell us more about the previous message from the documentation? I often use `composer install -o` on my computer (so in dev) and I never had some troubles. Is this still relevant?
I totally agree for the authoritative part, but the class map seems fine to me. I also create a basic reproducer where I rename some class, and everything was fine. Thanks

**Comment by Seldaek** [comment]
Classmap alone is fine if not authoritative, although it can hide misconfigurations/classes not in the correct PSR-4 path, although latest Composer now warns when it finds that, so that is not true anymore. The main issue is authoritative classmap + dev env IMO.

**Comment by fabpot** [comment]
Would it make sense then to make it the default in Composer itself?

**Comment by Seldaek** [comment]
IMO not really because of the performance hit when dumping the autoloader (I get 10x slowness here on Windows filesystem), and also the PSR-0/4 compliance warnings I mentioned above. This really only belongs on deployment/build process I'd say.

**Pull request merged**
