### PR TITLE
Move dotenv to "require"

### PR DESCRIPTION
**Pull request by nicolas-grekas**
This doesn't hurt anything and should ease using .env files without issues.

### CODE REVIEW

**Comment by sargath** [comment]
@nicolas-grekas @weaverryan sorry for re-opening this topic but I have just founded that, if you use 
`composer create-project symfony/website-skeleton my_project 3.4`
`symfony new --full my_project --version=3.4`

Basically, just like it is written in https://symfony.com/download, it will pull 3.4 website skeleton where dotenv still remains in require-dev.

**Comment by sargath** [comment]
Furthermore if you go to https://packagist.org/packages/symfony/website-skeleton#v3.4.0 you can still see that dotenv is in require-dev section.

**Comment by Pierstoval** [comment]
@sargath you don't want to download v3.4.0 of the website-skeleton, you need the latest version of it, which does not have Flex in require-dev: https://packagist.org/packages/symfony/website-skeleton#v3.4.21.2

**Comment by sargath** [comment]
@Pierstoval yes, so imho website docs should point to 3.4.21.2 instead --version=3.4

**Comment by sargath** [comment]
@Pierstoval  Check this out also.

```
sargath ~/Projects $ symfony new my_project --full --version=3.4
* Creating a new Symfony 3.4 project with Composer
  (running /home/sargath/.php-tools/bin/composer create-project symfony/website-skeleton my_project 3.4)

* Setting up the project under Git version control
  (running git init my_project)

                                                                                                                        
 [OK] Your project is now ready in /home/sargath/Projects/my_project                                                    
                                                                                                                        

sargath ~/Projects $ cat my_project/composer.json 
{
    "type": "project",
    "license": "proprietary",
    "require": {
        "php": "^7.0.8",
        "ext-iconv": "*",
        "sensio/framework-extra-bundle": "^5.1",
        "symfony/asset": "^3.4",
        "symfony/browser-kit": "^3.4",
        "symfony/console": "^3.4",
        "symfony/css-selector": "^3.4",
        "symfony/debug-pack": "*",
        "symfony/expression-language": "^3.4",
        "symfony/flex": "^1.0",
        "symfony/framework-bundle": "^3.4",
        "symfony/form": "^3.4",
        "symfony/lts": "^3",
        "symfony/orm-pack": "*",
        "symfony/monolog-bundle": "^3.1",
        "symfony/process": "^3.4",
        "symfony/security-bundle": "^3.4",
        "symfony/serializer-pack": "*",
        "symfony/validator": "^3.4",
        "symfony/swiftmailer-bundle": "^3.1",
        "symfony/web-link": "^3.4",
        "symfony/webpack-encore-pack": "*",
        "symfony/yaml": "^3.4"
    },
    "require-dev": {
        "symfony/dotenv": "^3.4",
        "symfony/maker-bundle": "^1.0",
        "symfony/phpunit-bridge": "^3.4",
        "symfony/profiler-pack": "*"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "id": "",
            "allow-contrib": false
        }
    }
}
```

**Comment by Pierstoval** [comment]
I think this is an issue with the Symfony CLI, not the skeleton.

Could you report this same issue in [symfonycorp/symfony-cli-issues](https://github.com/symfonycorp/symfony-cli-issues/issues)?

**Comment by sargath** [comment]
@Pierstoval sure no problem I can report this, but FYI same happens with pure composer 
```
composer create-project symfony/website-skeleton my_project 3.4
```

**Comment by nicolas-grekas** [comment]
This works:
`composer create-project symfony/website-skeleton my_project ^3.4`

**Comment by sargath** [comment]
Yeah sure, @nicolas-grekas after specifying versions it works, I know, but just wanted point this out since someone, that will just copy/paste link from website will get this version of composer.json with dotenv in -dev section and it may blow up on prod env.

**Comment by nicolas-grekas** [comment]
If you spotted places where things should be updated, please submit a PR to improve it!

**Comment by sargath** [comment]
@nicolas-grekas ok sorry :) I haven't been sure if this is a issue

**Comment by sargath** [comment]
... but anyway symfony website isn't probably open for creating PRs, am I right? :) What project would you propose where I can submit an issue or PR?

**Comment by nicolas-grekas** [comment]
@sargath fixed thanks, soon released if not already.

**Pull request merged**
